Configuration customization

diff --git a/images/dataverse/bin/config b/images/dataverse/bin/config
--- a/images/dataverse/bin/config
+++ b/images/dataverse/bin/config
@@ -2,55 +2,50 @@
 # This script configures varaibles used in other shell scripts.
 ################################################################################
 
-# Fail on any error
-set -euo pipefail
-
 # required for bash for loop if no files found
 shopt -s nullglob
 
 # Include some sane defaults
 . "${SCRIPT_DIR}/default.config"
 
-# Api defaults to locked state
-API_LOCKED=${API_LOCKED:-1}
-export API_LOCKED
-
 # Dataverse URL
-export DATAVERSE_SERVICE_HOST="${DATAVERSE_SERVICE_HOST:-"dataverse"}"
-export DATAVERSE_SERVICE_PORT_HTTP="${DATAVERSE_SERVICE_PORT_HTTP:-"8080"}"
-export DATAVERSE_URL="${DATAVERSE_URL:-"http://${DATAVERSE_SERVICE_HOST}:${DATAVERSE_SERVICE_PORT_HTTP}"}"
+DATAVERSE_SERVICE_HOST="${DATAVERSE_SERVICE_HOST:-"dataverse"}"
+DATAVERSE_SERVICE_PORT_HTTP="${DATAVERSE_SERVICE_PORT_HTTP:-"8080"}"
+DATAVERSE_URL="${DATAVERSE_URL:-"http://${DATAVERSE_SERVICE_HOST}:${DATAVERSE_SERVICE_PORT_HTTP}"}"
 
 # Solr URL
-export SOLR_SERVICE_HOST="${SOLR_SERVICE_HOST:-"solr"}"
-export SOLR_SERVICE_PORT_HTTP="${SOLR_SERVICE_PORT_HTTP:-"8983"}"
-export SOLR_URL="${SOLR_URL:-"http://${SOLR_SERVICE_HOST}:${SOLR_SERVICE_PORT_HTTP}"}"
+SOLR_SERVICE_HOST="${SOLR_SERVICE_HOST:-"solr"}"
+SOLR_SERVICE_PORT_HTTP="${SOLR_SERVICE_PORT_HTTP:-"8983"}"
+SOLR_URL="${SOLR_URL:-"http://${SOLR_SERVICE_HOST}:${SOLR_SERVICE_PORT_HTTP}"}"
 
 # Check and load secrets
-# if [ ! -s "${SECRETS_DIR}/db/password" ]; then
-#   echo "No database password present. Failing."
-#   exit 126
-# fi
-# export POSTGRES_PASSWORD=$(cat "${SECRETS_DIR}/db/password")
+if [ ! -s "${SECRETS_DIR}/db/password" ]; then
+  echo "No database password present. Failing."
+  exit 126
+fi
+POSTGRES_PASSWORD=$(cat "${SECRETS_DIR}/db/password")
 
 if [ ! -s "${SECRETS_DIR}/api/key" ]; then
   echo "No API key present. Failing."
   exit 126
 fi
-export API_KEY=$(cat "${SECRETS_DIR}/api/key")
+API_KEY=$(cat "${SECRETS_DIR}/api/key")
 
 if [ ! -s "${SECRETS_DIR}/api/userskey" ]; then
   echo "No Users API key present. Failing."
   exit 126
 fi
-export API_USERSKEY=$(cat "${SECRETS_DIR}/api/userskey")
+API_USERSKEY=$(cat "${SECRETS_DIR}/api/userskey")
+
+# Drop the Postgres credentials into .pgpass
+echo "${POSTGRES_SERVER}:*:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}" > ${HOME_DIR}/.pgpass
+chmod 0600 ${HOME_DIR}/.pgpass
 
 # Load dataverseAdmin password if present
 ADMIN_PASSWORD='admin'
-if [ "${ADMIN_PASSWORD}" = "" ] && [ -s "${SECRETS_DIR}/admin/password" ]; then
-  echo "Loading admin password from secret file."
+if [ -s "${SECRETS_DIR}/admin/password" ]; then
   ADMIN_PASSWORD=$(cat "${SECRETS_DIR}/admin/password")
 fi
-export ADMIN_PASSWORD
 
 check_reply () {
   echo "$REPLY" | jq -rM '.status' 2>/dev/null || echo -e 'FAILED\n' "$REPLY"
@@ -78,7 +73,8 @@ api_call () {
   # $@:3  other curl args
   local url="${DATAVERSE_URL}/api/${2}"
   local X='?' && [[ "$2" == *"$X"* ]] && X='&'
-  [[ ${API_LOCKED} -gt 0 ]] && url="${url}${X}unblock-key=${API_KEY}"
+  [[ "${API_LOCAL:-''}" == "true" ]] || url="${url}${X}unblock-key=${API_KEY}"
+  [[ "${API_DEBUG:-''}" == "true" ]] && echo " -- API call: ${1} ${@:3} $url"
   REPLY=$(curl -sS -X ${1} "${@:3}" "$url")
 }
 
@@ -88,6 +84,40 @@ json_call () {
 
 api() {
   api_call "$@"
-  STATUS=$(echo "${REPLY}" | jq -r '.status' 2>/dev/null || echo 'ERROR')
-  [[ "${STATUS}" == "OK" ]] || echo "API call '${2}' failed: $(echo "${REPLY}" | jq -r '.message' 2>/dev/null || echo "${REPLY}")"
+  local STATUS=$(jq -n "${REPLY}" | jq -r '.status' 2>/dev/null || echo 'ERROR')
+  [[ "${STATUS}" == "OK" ]] && return 0
+  local MESSAGE=$(jq -n "${REPLY}" | jq -r '.message' 2>/dev/null)
+  [[ "${MESSAGE}" == "null" ]] && MESSAGE="${REPLY}"
+  echo "API call '${2}' failed: ${MESSAGE}"
+  return -1
+}
+
+builtin_disable() {
+  echo "Disabling Builtin Users API"
+  api DELETE 'admin/settings/BuiltinUsers.KEY'
+  echo
+}
+
+builtin_enable() {
+  echo "Setting Builtin Users Key"
+  api PUT 'admin/settings/BuiltinUsers.KEY' -d "${API_USERSKEY}" 
+  echo
+}
+
+api_by_token() {
+  echo "Protecting admin API with token"
+  export API_LOCAL="false"
+  api PUT 'admin/settings/:BlockedApiKey' -d "${API_KEY}"
+  api PUT 'admin/settings/:BlockedApiPolicy' -d 'unblock-key'
+  api PUT 'admin/settings/:BlockedApiEndpoints' -d 'admin,builtin-users'
+  echo
+}
+
+api_only_local() {
+  echo "Restricting admin API to localhost only"
+  api DELETE 'admin/settings/:BlockedApiKey'
+  api PUT 'admin/settings/:BlockedApiPolicy' -d 'localhost-only'
+  api PUT  'admin/settings/:BlockedApiEndpoints' -d 'admin,builtin-users'
+  export API_LOCAL="true"
+  echo
 }
